modLoader = "javafml"
loaderVersion = "[33,)"
issueTrackerURL = "https://github.com/Iskallia/iSpawner/issues"
license = "GPL-3.0"

[[mods]]
modId = "ispawner"
version = "1.0"
displayName = "iSpawner"
authors = "KaptainWutax"
description = '''
Adds better spawner thingies.
'''
#logoFile = ""

[[dependencies.ispawner]]
modId = "forge"
mandatory = true
versionRange = "[33,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ispawner]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ispawner]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"